# Generated by Django 2.2.3 on 2019-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_file_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
